[project]
name = "renormalizer"
version = "0.0.11"
# dynamic = ["version"]
description = "Renormalizer is a Python based tensor network package with a special focus on electron-phonon quantum dynamics."

authors = [
    { name = "Weitang Li",     email = "liwt31@gmail.com"                 },
    { name = "Jiajun Ren",     email = "jjren@bnu.edu.cn"                 },
    { name = "Tong Jiang",     email = "tj.theochem@gmail.com"            },
    { name = "Yuanheng Wang",  email = "yuanhwangtheo@gmail.com"          },
    { name = "Yu Xiong",       email = "y-xiong22@mails.tsinghua.edu.cn"  },
    { name = "Cunxi Gong",     email = "ansatzMe@outlook.com"             },
    { name = "Jiace Sun",      email = "jsun3@caltech.edu"                }
]
maintainers = [{ name = "Weitang Li", email = "liwt31@gmail.com" }]

license = "Apache-2.0" 
readme = "README.md"
requires-python = ">=3.6,<3.12"

dependencies = [
    "numpy>=1.24",
    "scipy>=1.12,<1.13",
    "h5py>=3.1",
    "opt_einsum>=3.4",
    "sympy>=1.11",
    "print-tree2",
    "PyYAML",
    "qutip>=4.7.6,<5",
]

[project.optional-dependencies]
dev = [
    "pytest>=6.2",
    "black>=23.0,<24.0",
    "flake8>=6.0,<7.0",
]
docs = [
    "recommonmark",
    "furo",
    "nbsphinx",
    "sphinxcontrib-googleanalytics",
]
cupy = ["cupy>=13"]
cupynumeric = [
    "nvidia-cupynumeric>=25.3,<25.4; python_version == '3.10'",
    "nvidia-cupynumeric>=25.8; python_version >= '3.11'",
]
jax = ["jax>=0.5,<0.6", "jaxlib>=0.5,<0.6"]
jax-cuda12 = ["jax[cuda12]>=0.5,<0.6"]
primme = ["primme>=3.2,<4"]
pyscf = ["pyscf>=2.13,<3"]

[project.urls]
homepage = "https://github.com/shuaigroup/Renormalizer"
documentation = "https://shuaigroup.github.io/Renormalizer/"

[build-system]
requires = ["setuptools>=77.0.0"]
build-backend = "setuptools.build_meta"
