# -*- coding: utf-8 -*-

from renormalizer.backend.abstract import AbstractBackend
from renormalizer.backend.boundary import eye_like, flatten_backend, scalar_to_python
from renormalizer.backend.config import BackendConfig
from renormalizer.backend.execution import (
    ArrayInfo,
    BackendCapabilities,
    BackendCopyError,
    BackendFeatureError,
    BlockContractionSpec,
    BlockKey,
    BlockTensor,
    CommunicationPlan,
    ContractionPlan,
    ContractionStep,
    CopyPolicy,
    CostEstimate,
    DenseBlock,
    DeviceSpec,
    DeviceMesh,
    DistributedContractionPlan,
    DistributedContractionSpec,
    DistributedStepPlan,
    DistributedTensor,
    DistributionState,
    EinsumSpec,
    FallbackPolicy,
    GroupedGemmPlan,
    HardwareModel,
    LayoutSpec,
    LayoutTransform,
    MatmulDesc,
    MatmulPlan,
    PackedVectorSpec,
    PairContractionSpec,
    ShardingSpec,
    SlicedContractionPlan,
    StreamEvent,
    TensorOperand,
    Workspace,
    parse_device_spec,
)
from renormalizer.backend.factory import SUPPORTED_BACKENDS, available_backends, is_backend_available
from renormalizer.backend.gemm import (
    GemmTask,
    GroupedGemmStats,
    gemm_task_key,
    group_tasks_by_shape,
    grouped_gemm_fallback,
    grouped_gemm_stats,
    should_batch,
)
from renormalizer.backend.protocol import BackendProtocol
from renormalizer.backend.transforms import UnavailableTransforms

__all__ = [
    "AbstractBackend",
    "BackendConfig",
    "ArrayInfo",
    "BackendCapabilities",
    "BackendCopyError",
    "BackendFeatureError",
    "BackendProtocol",
    "BlockContractionSpec",
    "BlockKey",
    "BlockTensor",
    "CommunicationPlan",
    "ContractionPlan",
    "ContractionStep",
    "CopyPolicy",
    "CostEstimate",
    "DenseBlock",
    "DeviceMesh",
    "DeviceSpec",
    "DistributedContractionPlan",
    "DistributedContractionSpec",
    "DistributedStepPlan",
    "DistributedTensor",
    "DistributionState",
    "EinsumSpec",
    "FallbackPolicy",
    "GemmTask",
    "GroupedGemmPlan",
    "GroupedGemmStats",
    "HardwareModel",
    "LayoutSpec",
    "LayoutTransform",
    "MatmulDesc",
    "MatmulPlan",
    "PackedVectorSpec",
    "PairContractionSpec",
    "SUPPORTED_BACKENDS",
    "ShardingSpec",
    "SlicedContractionPlan",
    "StreamEvent",
    "TensorOperand",
    "UnavailableTransforms",
    "Workspace",
    "available_backends",
    "eye_like",
    "flatten_backend",
    "gemm_task_key",
    "group_tasks_by_shape",
    "grouped_gemm_fallback",
    "grouped_gemm_stats",
    "is_backend_available",
    "parse_device_spec",
    "scalar_to_python",
    "should_batch",
]
